name: vision_director
description: A tool to easily create vision videos with other people.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  # Displays a snackbar for feedback
  another_flushbar: ^1.12.29
  # Advanced custom video player
  better_player: ^0.0.83
  # Caches the network images
  cached_network_image: ^3.2.2
  # Collections and utilities functions and classes related to collections.
  collection: ^1.16.0
  # Functional Programming in Dart
  dartz: ^0.10.1
  # Http client
  dio: ^4.0.6
  # FFmpeg for Flutter
  ffmpeg_kit_flutter_full_gpl: ^5.1.0
  flutter:
    sdk: flutter
  # State Management
  flutter_bloc: ^8.1.1
  # Local state management
  flutter_hooks: ^0.18.5+1
  flutter_localizations:
    sdk: flutter
  # Markdown renderer
  flutter_markdown: ^0.6.12
  # Stores the JWT securely
  flutter_secure_storage: ^6.0.0
  # Slideable list item for deleting an item
  flutter_slidable: ^2.0.0
  # Record and play sound
  flutter_sound: ^9.2.13
  # Annotations for the freezed code-generator.
  freezed_annotation: ^2.1.0
  # Saves the file to the user's gallery
  gallery_saver: ^2.3.2
  # Service Locator / Dependeny Injection
  get_it: ^7.2.0
  # Key/Value store to save preferences
  hive: ^2.2.3
  # Mime Types
  http_parser: ^4.0.1
  # State Management that caches the data
  hydrated_bloc: ^8.1.0
  # Pick / Record images and videos
  image_picker: ^0.8.6
  # List that allows reordering the items via drag & drop
  implicitly_animated_reorderable_list: ^0.4.2
  # Code Generator for get_it
  injectable: ^1.5.3
  # internationalized/localized
  intl: ^0.17.0
  # Onboarding screens
  introduction_screen: ^3.0.2
  # JSON code generation
  json_annotation: ^4.7.0
  # Advanced bottom sheet
  modal_bottom_sheet: ^2.1.2
  # path manipulation library
  path: ^1.8.2
  # Flutter plugin for getting commonly used locations on host platform file systems
  path_provider: ^2.0.11
  # A timer implementation that can be paused, resumed and reset
  pausable_timer: ^1.0.0+6
  # Simplefies Android permissions
  permission_handler: ^10.1.0
  # Zoomable image screen
  photo_view: ^0.14.0
  # Handles the SignalR connection
  signalr_netcore: ^1.3.3
  # Helper for displaying time
  timeago: ^3.3.0
  # Launch Email
  url_launcher: ^6.1.6
  # Generate UUIDs
  uuid: ^3.0.6
  # Simple video player
  video_player: ^2.4.7
  # Generates the thumbnails
  video_thumbnail: ^0.5.3
  # Keeps the screen from going to sleep
  wakelock: ^0.6.2

dev_dependencies:
  bloc_test: ^9.1.0
  build_runner: null
  flutter_launcher_icons: ^0.10.0
  flutter_native_splash: ^2.2.11
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  injectable_generator: ^1.5.4
  json_serializable: null
  lint: ^1.10.0
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/logo.png
    - assets/resources/
    - assets/onboarding/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"

flutter_native_splash:
  color: "#303030"
  image: assets/logo.png
