/// [Guidelines] contains constants related to vision video guidelines.
class Guidelines {
  /// Maximum duration of a step in seconds.
  static const maxDuration = 30;

  /// Maximum duration of the scenario in seconds (5 Minutes).
  static const maxTotalDuration = 300;

  /// Maximum number of steps.
  static const maxSteps = 20;

  /// Default / Minimum duration of a step.
  static const defaultDuration = 15;

  /// Maximum file size in bytes (100MB).
  static const maxFileSize = 100 * 1024 * 1024;

  /// Maximum size of the exported vision video.
  static const maxVisionVideoSize = maxFileSize * maxSteps;

  /// Duration the title will be displayed in seconds.
  static const titleLength = 5;

  /// Duration the credits will be displayed in seconds.
  static const creditsLength = 5;

  /// Duration of all the automatically generated videos.
  static const autoGeneratedLength = titleLength + creditsLength;
}

/// Enum containing all supported export resolutions
///
/// * [hd] 720p [1280x720]
/// * [fhd] 1080p [1920x1080]
enum ExportResolution {
  /// 720p [1280x720]
  hd,

  /// 1080p [1920x1080]
  fhd,
}

/// [AppConstants] contains constants that apply to the whole app.
class AppConstants {
  static const tokenKey = "token";
  static const mediaDirectory = "media";
}
